import Link from 'next/link'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Terms of Service — PDF Book Page Trimmer',
  description: 'Terms and conditions for using our PDF trimming service.',
}

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-gray-50">
      <header className="bg-gradient-to-r from-purple-600 to-purple-800 text-white shadow-lg">
        <div className="container mx-auto px-4 py-4">
          <div className="flex items-center justify-between">
            <Link href="/" className="text-2xl font-bold hover:opacity-90">
              PDF Book Page Trimmer
            </Link>
            <nav className="flex gap-6 text-sm">
              <Link href="/faq" className="hover:underline">FAQ</Link>
              <Link href="/contact" className="hover:underline">Contact</Link>
              <Link href="/privacy" className="hover:underline">Privacy</Link>
              <Link href="/terms" className="hover:underline font-semibold">Terms</Link>
            </nav>
          </div>
        </div>
      </header>

      <main className="container mx-auto px-4 py-12 max-w-4xl">
        <article className="bg-white rounded-lg shadow-sm border p-8 md:p-12">
          <h1 className="text-4xl font-bold text-gray-900 mb-6">Terms of Service</h1>
          <p className="text-sm text-gray-600 mb-8">Last updated: {new Date().toLocaleDateString()}</p>

          <div className="prose prose-lg max-w-none">
            <h2>1. Acceptance of Terms</h2>
            <p>
              By accessing and using PDF Book Page Trimmer ("the Service"), you accept and agree to be bound by these
              Terms of Service. If you do not agree to these terms, please do not use the Service.
            </p>

            <h2>2. Description of Service</h2>
            <p>
              PDF Book Page Trimmer provides a web-based tool that allows users to upload PDF files, apply crop settings
              to left and right pages independently, preview the results, and export selected pages as image files in
              various formats (JPG, PNG, TIFF, WebP).
            </p>

            <h2>3. User Responsibilities</h2>
            
            <h3>3.1 Lawful Use</h3>
            <p>
              You agree to use the Service only for lawful purposes and in accordance with these Terms. You must not:
            </p>
            <ul>
              <li>Upload or process content that infringes on intellectual property rights of others</li>
              <li>Upload malicious files, viruses, or harmful code</li>
              <li>Attempt to gain unauthorized access to our systems or other users' data</li>
              <li>Use the Service to process content that is illegal, defamatory, obscene, or offensive</li>
              <li>Violate any applicable local, state, national, or international law</li>
            </ul>

            <h3>3.2 Copyright and Intellectual Property</h3>
            <p>
              You represent and warrant that you have the necessary rights, licenses, or permissions to upload and
              process any PDF files you submit to the Service. You are solely responsible for ensuring that you have
              the right to process and export the content contained in your PDFs.
            </p>
            <p>
              <strong>Important:</strong> This tool is intended for personal use with content you own or have permission
              to modify. Do not use this service to process copyrighted books, documents, or materials unless you hold
              the copyright or have explicit permission from the copyright holder.
            </p>

            <h3>3.3 Account and Security</h3>
            <p>
              The Service does not require account creation. However, you are responsible for:
            </p>
            <ul>
              <li>Maintaining the security of your device and internet connection</li>
              <li>Any activity that occurs through your use of the Service</li>
              <li>Ensuring your browser and software are up to date for optimal security</li>
            </ul>

            <h2>4. Ownership of Export Results</h2>
            <p>
              You retain all rights to the image files generated by processing your PDFs through the Service, subject
              to the condition that you had the right to process the source PDF content. We claim no ownership or
              rights over your exported files.
            </p>

            <h2>5. Service Availability and Modifications</h2>
            
            <h3>5.1 Availability</h3>
            <p>
              We strive to provide reliable service but do not guarantee uninterrupted or error-free operation. The
              Service may be unavailable due to:
            </p>
            <ul>
              <li>Maintenance and updates</li>
              <li>Technical difficulties</li>
              <li>Circumstances beyond our control</li>
            </ul>

            <h3>5.2 Modifications</h3>
            <p>
              We reserve the right to modify, suspend, or discontinue the Service (or any part thereof) at any time
              with or without notice. We shall not be liable to you or any third party for any modification,
              suspension, or discontinuation of the Service.
            </p>

            <h2>6. Limitations and Restrictions</h2>
            <ul>
              <li><strong>File size limit:</strong> Maximum PDF file size is 100MB</li>
              <li><strong>Processing limits:</strong> We may implement rate limiting to prevent abuse</li>
              <li><strong>Storage time:</strong> Uploaded files are automatically deleted within 1 hour</li>
              <li><strong>Fair use:</strong> Excessive or abusive use may result in access restrictions</li>
            </ul>

            <h2>7. Disclaimers and Limitation of Liability</h2>
            
            <h3>7.1 No Warranty</h3>
            <p>
              THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR
              IMPLIED, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
              PURPOSE, OR NON-INFRINGEMENT.
            </p>
            <p>
              We do not warrant that:
            </p>
            <ul>
              <li>The Service will meet your specific requirements</li>
              <li>The Service will be uninterrupted, timely, secure, or error-free</li>
              <li>The results obtained from using the Service will be accurate or reliable</li>
              <li>Any errors in the Service will be corrected</li>
            </ul>

            <h3>7.2 Limitation of Liability</h3>
            <p>
              TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL WE BE LIABLE FOR ANY INDIRECT, INCIDENTAL,
              SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING WITHOUT LIMITATION, LOSS OF PROFITS, DATA, USE,
              GOODWILL, OR OTHER INTANGIBLE LOSSES, RESULTING FROM:
            </p>
            <ul>
              <li>Your use or inability to use the Service</li>
              <li>Any unauthorized access to or use of our servers and/or any personal information stored therein</li>
              <li>Any bugs, viruses, or harmful code transmitted through the Service</li>
              <li>Any errors or omissions in any content or for any loss or damage incurred as a result of your use of any content posted, emailed, transmitted, or otherwise made available through the Service</li>
            </ul>

            <h3>7.3 Quality of Results</h3>
            <p>
              While we strive to provide accurate cropping and high-quality exports, we do not guarantee that:
            </p>
            <ul>
              <li>The exported images will meet your specific quality requirements</li>
              <li>The cropping will be perfect for all types of PDFs</li>
              <li>Complex or unusual PDF formats will process correctly</li>
            </ul>
            <p>
              We strongly recommend reviewing preview images before processing your entire PDF.
            </p>

            <h2>8. Indemnification</h2>
            <p>
              You agree to indemnify, defend, and hold harmless PDF Book Page Trimmer, its operators, affiliates, and
              service providers from any claims, damages, losses, liabilities, and expenses (including reasonable
              attorneys' fees) arising out of or related to:
            </p>
            <ul>
              <li>Your use of the Service</li>
              <li>Your violation of these Terms</li>
              <li>Your violation of any rights of another party, including intellectual property rights</li>
              <li>Any content you upload or process through the Service</li>
            </ul>

            <h2>9. Privacy</h2>
            <p>
              Your use of the Service is also governed by our <Link href="/privacy" className="text-purple-600 hover:underline">Privacy Policy</Link>.
              Please review it to understand how we collect, use, and protect your information.
            </p>

            <h2>10. Third-Party Services</h2>
            <p>
              The Service may contain links to third-party websites or services (such as Google AdSense) that are not
              owned or controlled by us. We have no control over, and assume no responsibility for, the content,
              privacy policies, or practices of any third-party websites or services.
            </p>

            <h2>11. Termination</h2>
            <p>
              We reserve the right to terminate or suspend your access to the Service immediately, without prior notice
              or liability, for any reason, including without limitation if you breach these Terms.
            </p>

            <h2>12. Governing Law and Jurisdiction</h2>
            <p>
              These Terms shall be governed by and construed in accordance with the laws of the jurisdiction in which
              the Service operator is located, without regard to its conflict of law provisions.
            </p>
            <p>
              Any disputes arising out of or related to these Terms or the Service shall be resolved in the courts of
              competent jurisdiction in that location.
            </p>

            <h2>13. Changes to Terms</h2>
            <p>
              We reserve the right to modify these Terms at any time. We will notify users of significant changes by
              posting a notice on the website. Your continued use of the Service after such modifications constitutes
              your acceptance of the updated Terms.
            </p>

            <h2>14. Severability</h2>
            <p>
              If any provision of these Terms is found to be unenforceable or invalid, that provision shall be limited
              or eliminated to the minimum extent necessary, and the remaining provisions shall remain in full force
              and effect.
            </p>

            <h2>15. Entire Agreement</h2>
            <p>
              These Terms, together with the Privacy Policy, constitute the entire agreement between you and PDF Book
              Page Trimmer regarding the use of the Service.
            </p>

            <h2>16. Contact Information</h2>
            <p>
              If you have questions about these Terms, please contact us:
            </p>
            <ul>
              <li>Email: <a href="mailto:admin@ripstuff.net" className="text-purple-600 hover:underline">admin@ripstuff.net</a></li>
              <li>Contact Form: <Link href="/contact" className="text-purple-600 hover:underline">Contact Page</Link></li>
            </ul>

            <h2>17. Acknowledgment</h2>
            <p>
              BY USING THE SERVICE, YOU ACKNOWLEDGE THAT YOU HAVE READ THESE TERMS OF SERVICE AND AGREE TO BE BOUND BY THEM.
            </p>
          </div>
        </article>

        <div className="mt-8 text-center">
          <Link
            href="/"
            className="inline-block px-6 py-3 bg-gradient-to-r from-purple-600 to-purple-800 text-white rounded-lg hover:from-purple-700 hover:to-purple-900 font-semibold"
          >
            Back to Home
          </Link>
        </div>
      </main>
    </div>
  )
}
